//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmkLearningKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VmkLearningKit.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки успешно обновлены!.
        /// </summary>
        internal static string ACCOUNT_SETTINGS_IS_UPDATED {
            get {
                return ResourceManager.GetString("ACCOUNT_SETTINGS_IS_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        internal static string FIELD_MUST_NOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("FIELD_MUST_NOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eВМК – электронный ВМК.
        /// </summary>
        internal static string MAIN_TITLE {
            get {
                return ResourceManager.GetString("MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить настройки преподавателя.
        /// </summary>
        internal static string PROFESSOR_SETTINGS_IS_NOT_UPDATED {
            get {
                return ResourceManager.GetString("PROFESSOR_SETTINGS_IS_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить настройки пользователя.
        /// </summary>
        internal static string USER_SETTINGS_IS_NOT_UPDATED {
            get {
                return ResourceManager.GetString("USER_SETTINGS_IS_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким NickName уже зарегестрирован.
        /// </summary>
        internal static string USER_WITH_THE_SAME_NICKNAME_EXISTS {
            get {
                return ResourceManager.GetString("USER_WITH_THE_SAME_NICKNAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный логин или пароль.
        /// </summary>
        internal static string WRONG_USER_LOGIN_OR_PASSWD {
            get {
                return ResourceManager.GetString("WRONG_USER_LOGIN_OR_PASSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша роль на портале неопределена, свяжитесь с администратором.
        /// </summary>
        internal static string WRONG_USER_ROLE {
            get {
                return ResourceManager.GetString("WRONG_USER_ROLE", resourceCulture);
            }
        }
    }
}
