<?xml version="1.0" encoding="utf-8"?>
<Database Name="ULKDB" Class="MvcULKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ULKDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ULKDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.departments" Member="departments">
    <Type Name="department">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="department_discipline" Member="disciplines" ThisKey="id" OtherKey="department_id" Type="discipline" />
    </Type>
  </Table>
  <Table Name="dbo.disciplines" Member="disciplines">
    <Type Name="discipline">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="department_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="discipline_topic" Member="topics" ThisKey="id" OtherKey="discipline_id" Type="topic" />
      <Association Name="department_discipline" Member="department" ThisKey="department_id" OtherKey="id" Type="department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.razdels" Member="razdels">
    <Type Name="razdel">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="topic_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="questions_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="razdel_question" Member="questions" ThisKey="id" OtherKey="razdel_id" Type="question" />
      <Association Name="topic_razdel" Member="topic" ThisKey="topic_id" OtherKey="id" Type="topic" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.topics" Member="topics">
    <Type Name="topic">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="discipline_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="topic_razdel" Member="razdels" ThisKey="id" OtherKey="topic_id" Type="razdel" />
      <Association Name="discipline_topic" Member="discipline" ThisKey="discipline_id" OtherKey="id" Type="discipline" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.questions" Member="questions">
    <Type Name="question">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="razdel_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="assigned_count" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="right_answers_count" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="wrong_answers_count" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="double_group" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="exclusion_group" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="is_deleted" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="question_answer" Member="answers" ThisKey="id" OtherKey="question_id" Type="answer" />
      <Association Name="razdel_question" Member="razdel" ThisKey="razdel_id" OtherKey="id" Type="razdel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.answers" Member="answers">
    <Type Name="answer">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="question_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="score" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="question_answer" Member="question" ThisKey="question_id" OtherKey="id" Type="question" IsForeignKey="true" />
    </Type>
  </Table>
</Database>