//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmkLearningKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VmkLearningKit.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string ABBREVIATION_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("ABBREVIATION_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT_ACTION_NAME {
            get {
                return ResourceManager.GetString("ABOUT_ACTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Chair/.
        /// </summary>
        internal static string ADMIN_CHAIR_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_CHAIR_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Department/.
        /// </summary>
        internal static string ADMIN_DEPARTMENT_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_DEPARTMENT_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/EducationPlan/.
        /// </summary>
        internal static string ADMIN_EDUCATION_PLAN_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_EDUCATION_PLAN_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Group/.
        /// </summary>
        internal static string ADMIN_GROUP_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_GROUP_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminNavigation.
        /// </summary>
        internal static string ADMIN_NAVIGAITON {
            get {
                return ResourceManager.GetString("ADMIN_NAVIGAITON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администраторская панель.
        /// </summary>
        internal static string ADMIN_PANEL_TITLE {
            get {
                return ResourceManager.GetString("ADMIN_PANEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string ADMIN_ROLE {
            get {
                return ResourceManager.GetString("ADMIN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/SpecialityDiscipline/.
        /// </summary>
        internal static string ADMIN_SPECIALITY_DISCIPLINE_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_SPECIALITY_DISCIPLINE_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Speciality/.
        /// </summary>
        internal static string ADMIN_SPECIALITY_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_SPECIALITY_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Specialization/.
        /// </summary>
        internal static string ADMIN_SPECIALIZATION_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_SPECIALIZATION_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/User/.
        /// </summary>
        internal static string ADMIN_USER_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_USER_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/.
        /// </summary>
        internal static string ADMIN_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ALIAS_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("ALIAS_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Cabinet/General/.
        /// </summary>
        internal static string CABINET_GENERAL_VIEWS {
            get {
                return ResourceManager.GetString("CABINET_GENERAL_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Cabinet/Student/.
        /// </summary>
        internal static string CABINET_STUDENT_VIEWS {
            get {
                return ResourceManager.GetString("CABINET_STUDENT_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Cabinet/.
        /// </summary>
        internal static string CABINET_URL {
            get {
                return ResourceManager.GetString("CABINET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Cabinet/.
        /// </summary>
        internal static string CABINET_VIEWS {
            get {
                return ResourceManager.GetString("CABINET_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChairMenu.
        /// </summary>
        internal static string CHAIR_MENU {
            get {
                return ResourceManager.GetString("CHAIR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLK_DBConnectionString.
        /// </summary>
        internal static string CONNECTION_STRING_NAME {
            get {
                return ResourceManager.GetString("CONNECTION_STRING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseName.
        /// </summary>
        internal static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятница.
        /// </summary>
        internal static string DAY_FRIDAY {
            get {
                return ResourceManager.GetString("DAY_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понедельник.
        /// </summary>
        internal static string DAY_MONDAY {
            get {
                return ResourceManager.GetString("DAY_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суббота.
        /// </summary>
        internal static string DAY_SATURDAY {
            get {
                return ResourceManager.GetString("DAY_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воскресенье.
        /// </summary>
        internal static string DAY_SUNDAY {
            get {
                return ResourceManager.GetString("DAY_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четверг.
        /// </summary>
        internal static string DAY_THURSDAY {
            get {
                return ResourceManager.GetString("DAY_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторник.
        /// </summary>
        internal static string DAY_TUESDAY {
            get {
                return ResourceManager.GetString("DAY_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среда.
        /// </summary>
        internal static string DAY_WEDNESDAY {
            get {
                return ResourceManager.GetString("DAY_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbBackup_.
        /// </summary>
        internal static string DB_BACKUP_NAME {
            get {
                return ResourceManager.GetString("DB_BACKUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /DbBackups/.
        /// </summary>
        internal static string DB_BACKUP_PATH {
            get {
                return ResourceManager.GetString("DB_BACKUP_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbDataFilePath.
        /// </summary>
        internal static string DB_DATA_FILE_PATH {
            get {
                return ResourceManager.GetString("DB_DATA_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbLogFilePath.
        /// </summary>
        internal static string DB_LOG_FILE_PATH {
            get {
                return ResourceManager.GetString("DB_LOG_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string DEFAULT_CHAIR_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_CHAIR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @unn.ru.
        /// </summary>
        internal static string DEFAULT_EMAIL_DOMEN {
            get {
                return ResourceManager.GetString("DEFAULT_EMAIL_DOMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижняя.
        /// </summary>
        internal static string DOWN_WEEK {
            get {
                return ResourceManager.GetString("DOWN_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Error/404.
        /// </summary>
        internal static string ERROR_404_URL {
            get {
                return ResourceManager.GetString("ERROR_404_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Error/.
        /// </summary>
        internal static string ERROR_URL {
            get {
                return ResourceManager.GetString("ERROR_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждая.
        /// </summary>
        internal static string EVERY_WEEK {
            get {
                return ResourceManager.GetString("EVERY_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Uploads/Excel/.
        /// </summary>
        internal static string EXCEL_FILE_UPLOAD_PATH {
            get {
                return ResourceManager.GetString("EXCEL_FILE_UPLOAD_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        internal static string FIELD_MUST_NOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("FIELD_MUST_NOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string FORM_MESSAGE {
            get {
                return ResourceManager.GetString("FORM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralMenu.
        /// </summary>
        internal static string GENERAL_MENU {
            get {
                return ResourceManager.GetString("GENERAL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralNavigation.
        /// </summary>
        internal static string GENERAL_NAVIGATION {
            get {
                return ResourceManager.GetString("GENERAL_NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string GROUP_DEFAULT_ALIAS {
            get {
                return ResourceManager.GetString("GROUP_DEFAULT_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        internal static string HASH_ALGORITHM {
            get {
                return ResourceManager.GetString("HASH_ALGORITHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home.
        /// </summary>
        internal static string HOME_URL {
            get {
                return ResourceManager.GetString("HOME_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuType.
        /// </summary>
        internal static string MENU_TYPE {
            get {
                return ResourceManager.GetString("MENU_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodist.
        /// </summary>
        internal static string METODIST_ROLE {
            get {
                return ResourceManager.GetString("METODIST_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationType.
        /// </summary>
        internal static string NAVIGATION_TYPE {
            get {
                return ResourceManager.GetString("NAVIGATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NONE_ROLE {
            get {
                return ResourceManager.GetString("NONE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageTitle.
        /// </summary>
        internal static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartialViewError.
        /// </summary>
        internal static string PARTIALVIEW_PAGE_ERROR {
            get {
                return ResourceManager.GetString("PARTIALVIEW_PAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        internal static string PERSON_CABINET {
            get {
                return ResourceManager.GetString("PERSON_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторная работа / Терминал-класс.
        /// </summary>
        internal static string PRACTICE_TYPE_LAB {
            get {
                return ResourceManager.GetString("PRACTICE_TYPE_LAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практика.
        /// </summary>
        internal static string PRACTICE_TYPE_PRACTICE {
            get {
                return ResourceManager.GetString("PRACTICE_TYPE_PRACTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_ABOUT {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_DEGREE {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor_None.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_LOGIN {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor_None.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_NICKNAME {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_POSITION {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfessorMenu.
        /// </summary>
        internal static string PROFESSOR_MENU {
            get {
                return ResourceManager.GetString("PROFESSOR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string PROFESSOR_ROLE {
            get {
                return ResourceManager.GetString("PROFESSOR_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professors.
        /// </summary>
        internal static string PROFESSORS_ACTION_NAME {
            get {
                return ResourceManager.GetString("PROFESSORS_ACTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([1-9]\d*\.\d+)|([1-9]\d*)|([0])|([0]\.d+).
        /// </summary>
        internal static string REGULAR_EXPRESSION_VALUE_WITH_POINT {
            get {
                return ResourceManager.GetString("REGULAR_EXPRESSION_VALUE_WITH_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to экзамен.
        /// </summary>
        internal static string REPORTING_TYPE_EXAM {
            get {
                return ResourceManager.GetString("REPORTING_TYPE_EXAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to курсовая работа.
        /// </summary>
        internal static string REPORTING_TYPE_SCIENTIFIC_WORK {
            get {
                return ResourceManager.GetString("REPORTING_TYPE_SCIENTIFIC_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зачет.
        /// </summary>
        internal static string REPORTING_TYPE_ZACHOT {
            get {
                return ResourceManager.GetString("REPORTING_TYPE_ZACHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SESSION_USER {
            get {
                return ResourceManager.GetString("SESSION_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAuth.
        /// </summary>
        internal static string SESSION_USER_AUTH {
            get {
                return ResourceManager.GetString("SESSION_USER_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLogin.
        /// </summary>
        internal static string SESSION_USER_LOGIN {
            get {
                return ResourceManager.GetString("SESSION_USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string SESSION_USER_NAME {
            get {
                return ResourceManager.GetString("SESSION_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole.
        /// </summary>
        internal static string SESSION_USER_ROLE {
            get {
                return ResourceManager.GetString("SESSION_USER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальности и специализации.
        /// </summary>
        internal static string SPECIALITIES_TITLE {
            get {
                return ResourceManager.GetString("SPECIALITIES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialityAlias.
        /// </summary>
        internal static string SPECIALITY_ALIAS {
            get {
                return ResourceManager.GetString("SPECIALITY_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано.
        /// </summary>
        internal static string STRING_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("STRING_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studnet_None.
        /// </summary>
        internal static string STUDENT_DEFAULT_LOGIN {
            get {
                return ResourceManager.GetString("STUDENT_DEFAULT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student_None.
        /// </summary>
        internal static string STUDENT_DEFAULT_NICKNAME {
            get {
                return ResourceManager.GetString("STUDENT_DEFAULT_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        internal static string STUDENT_DEFAULT_SECOND_NAME {
            get {
                return ResourceManager.GetString("STUDENT_DEFAULT_SECOND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string STUDENT_ROLE {
            get {
                return ResourceManager.GetString("STUDENT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Cabinet/Timetable/.
        /// </summary>
        internal static string STUDENT_TIMETABLE_URL {
            get {
                return ResourceManager.GetString("STUDENT_TIMETABLE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано.
        /// </summary>
        internal static string TERM_DEFAULT_REPORTING {
            get {
                return ResourceManager.GetString("TERM_DEFAULT_REPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхняя.
        /// </summary>
        internal static string UP_WEEK {
            get {
                return ResourceManager.GetString("UP_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string VIEW_PAGE_ERROR {
            get {
                return ResourceManager.GetString("VIEW_PAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error404.
        /// </summary>
        internal static string VIEW_PAGE_ERROR_404 {
            get {
                return ResourceManager.GetString("VIEW_PAGE_ERROR_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMK.
        /// </summary>
        internal static string VMK_DEPARTMENT_ALIAS {
            get {
                return ResourceManager.GetString("VMK_DEPARTMENT_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abbreviation.
        /// </summary>
        internal static string XML_ATTRIBUTE_ABBREVIATION {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building.
        /// </summary>
        internal static string XML_ATTRIBUTE_BUILDING {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chairAbbreviation.
        /// </summary>
        internal static string XML_ATTRIBUTE_CHAIR_ABBREVIATION {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_CHAIR_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string XML_ATTRIBUTE_CODE {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        internal static string XML_ATTRIBUTE_COUNT {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dayOfWeek.
        /// </summary>
        internal static string XML_ATTRIBUTE_DAY_OF_WEEK {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_DAY_OF_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degree.
        /// </summary>
        internal static string XML_ATTRIBUTE_DEGREE {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to educationPlan.
        /// </summary>
        internal static string XML_ATTRIBUTE_EDUCATION_PLAN {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_EDUCATION_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstName.
        /// </summary>
        internal static string XML_ATTRIBUTE_FIRSTNAME {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groupNumber.
        /// </summary>
        internal static string XML_ATTRIBUTE_GROUP_NUMBER {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_GROUP_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labs.
        /// </summary>
        internal static string XML_ATTRIBUTE_LABS {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_LABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastName.
        /// </summary>
        internal static string XML_ATTRIBUTE_LASTNAME {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lections.
        /// </summary>
        internal static string XML_ATTRIBUTE_LECTIONS {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_LECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level.
        /// </summary>
        internal static string XML_ATTRIBUTE_LEVEL {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string XML_ATTRIBUTE_NAME {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string XML_ATTRIBUTE_NUMBER {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part.
        /// </summary>
        internal static string XML_ATTRIBUTE_PART {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patronymic.
        /// </summary>
        internal static string XML_ATTRIBUTE_PATRONYMIC {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_PATRONYMIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        internal static string XML_ATTRIBUTE_POSITION {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practices.
        /// </summary>
        internal static string XML_ATTRIBUTE_PRACTICES {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_PRACTICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rank.
        /// </summary>
        internal static string XML_ATTRIBUTE_RANK {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_RANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reportings.
        /// </summary>
        internal static string XML_ATTRIBUTE_REPORTINGS {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_REPORTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to room.
        /// </summary>
        internal static string XML_ATTRIBUTE_ROOM {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site.
        /// </summary>
        internal static string XML_ATTRIBUTE_SITE {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specialityAbbreviation.
        /// </summary>
        internal static string XML_ATTRIBUTE_SPECIALITY_ABBREVIATION {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_SPECIALITY_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specializationAbbreviation.
        /// </summary>
        internal static string XML_ATTRIBUTE_SPECIALIZATION_ABBREVIATION {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_SPECIALIZATION_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teacher.
        /// </summary>
        internal static string XML_ATTRIBUTE_TEACHER {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_TEACHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string XML_ATTRIBUTE_TIME {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string XML_ATTRIBUTE_TITLE {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string XML_ATTRIBUTE_WEEK {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string XML_ATTRIBUTE_WEEKS {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_WEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой кафедры не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_CHAIR {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого дня недели не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_DAY_OF_WEEK {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_DAY_OF_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой дисциплины не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_DISCIPLINE {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_DISCIPLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого образовательного плана не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_EDUCATION_PLAN {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_EDUCATION_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой группы не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_GROUP {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого преподавателя не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_PROFESSOR {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_PROFESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая дисциплина не читается данным преподавателем.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_PROFESSOR_OF_DISCIPLINE {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_PROFESSOR_OF_DISCIPLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип отчетности.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_REPORTING {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_REPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой специальности не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_SPECIALITY {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_SPECIALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой специализации не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_SPECIALIZATION {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_SPECIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой недели не существует.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_EXIST_WEEK {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_EXIST_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные имеют неправильный формат.
        /// </summary>
        internal static string XML_DATA_ERROR_NOT_VALID_FORMAT {
            get {
                return ResourceManager.GetString("XML_DATA_ERROR_NOT_VALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional.
        /// </summary>
        internal static string XML_ELEMENT_ADDITIONAL {
            get {
                return ResourceManager.GetString("XML_ELEMENT_ADDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to applicationDomain.
        /// </summary>
        internal static string XML_ELEMENT_APPLICATION_DOMAIN {
            get {
                return ResourceManager.GetString("XML_ELEMENT_APPLICATION_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category1.
        /// </summary>
        internal static string XML_ELEMENT_CATEGORY_1 {
            get {
                return ResourceManager.GetString("XML_ELEMENT_CATEGORY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category2.
        /// </summary>
        internal static string XML_ELEMENT_CATEGORY_2 {
            get {
                return ResourceManager.GetString("XML_ELEMENT_CATEGORY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chair.
        /// </summary>
        internal static string XML_ELEMENT_CHAIR {
            get {
                return ResourceManager.GetString("XML_ELEMENT_CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discipline.
        /// </summary>
        internal static string XML_ELEMENT_DISCIPLINE {
            get {
                return ResourceManager.GetString("XML_ELEMENT_DISCIPLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disciplineProgram.
        /// </summary>
        internal static string XML_ELEMENT_DISCIPLINE_PROGRAM {
            get {
                return ResourceManager.GetString("XML_ELEMENT_DISCIPLINE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disciplineRazdels.
        /// </summary>
        internal static string XML_ELEMENT_DISCIPLINE_RAZDELS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_DISCIPLINE_RAZDELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disciplineRazdelsContent.
        /// </summary>
        internal static string XML_ELEMENT_DISCIPLINE_RAZDELS_CONTENT {
            get {
                return ResourceManager.GetString("XML_ELEMENT_DISCIPLINE_RAZDELS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disciplineVolume.
        /// </summary>
        internal static string XML_ELEMENT_DISCIPLINE_VOLUME {
            get {
                return ResourceManager.GetString("XML_ELEMENT_DISCIPLINE_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to educationPlan.
        /// </summary>
        internal static string XML_ELEMENT_EDUCATION_PLAN {
            get {
                return ResourceManager.GetString("XML_ELEMENT_EDUCATION_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string XML_ELEMENT_GROUP {
            get {
                return ResourceManager.GetString("XML_ELEMENT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lab.
        /// </summary>
        internal static string XML_ELEMENT_LAB {
            get {
                return ResourceManager.GetString("XML_ELEMENT_LAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labPractice.
        /// </summary>
        internal static string XML_ELEMENT_LAB_PRACTICE {
            get {
                return ResourceManager.GetString("XML_ELEMENT_LAB_PRACTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lection.
        /// </summary>
        internal static string XML_ELEMENT_LECTION {
            get {
                return ResourceManager.GetString("XML_ELEMENT_LECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lections.
        /// </summary>
        internal static string XML_ELEMENT_LECTIONS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_LECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literature.
        /// </summary>
        internal static string XML_ELEMENT_LITERATURE {
            get {
                return ResourceManager.GetString("XML_ELEMENT_LITERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to markCriterias.
        /// </summary>
        internal static string XML_ELEMENT_MARK_CRITERIAS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_MARK_CRITERIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practice.
        /// </summary>
        internal static string XML_ELEMENT_PRACTICE {
            get {
                return ResourceManager.GetString("XML_ELEMENT_PRACTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purposes.
        /// </summary>
        internal static string XML_ELEMENT_PURPOSES {
            get {
                return ResourceManager.GetString("XML_ELEMENT_PURPOSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questions.
        /// </summary>
        internal static string XML_ELEMENT_QUESTIONS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporting.
        /// </summary>
        internal static string XML_ELEMENT_REPORTING {
            get {
                return ResourceManager.GetString("XML_ELEMENT_REPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirements.
        /// </summary>
        internal static string XML_ELEMENT_REQUIREMENTS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_REQUIREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speciality.
        /// </summary>
        internal static string XML_ELEMENT_SPECIALITY {
            get {
                return ResourceManager.GetString("XML_ELEMENT_SPECIALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specialization.
        /// </summary>
        internal static string XML_ELEMENT_SPECIALIZATION {
            get {
                return ResourceManager.GetString("XML_ELEMENT_SPECIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specializations.
        /// </summary>
        internal static string XML_ELEMENT_SPECIALIZATIONS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_SPECIALIZATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student.
        /// </summary>
        internal static string XML_ELEMENT_STUDENT {
            get {
                return ResourceManager.GetString("XML_ELEMENT_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teacher.
        /// </summary>
        internal static string XML_ELEMENT_TEACHER {
            get {
                return ResourceManager.GetString("XML_ELEMENT_TEACHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teachers.
        /// </summary>
        internal static string XML_ELEMENT_TEACHERS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_TEACHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term.
        /// </summary>
        internal static string XML_ELEMENT_TERM {
            get {
                return ResourceManager.GetString("XML_ELEMENT_TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms.
        /// </summary>
        internal static string XML_ELEMENT_TERMS {
            get {
                return ResourceManager.GetString("XML_ELEMENT_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string XML_ELEMENT_TITLE {
            get {
                return ResourceManager.GetString("XML_ELEMENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topic.
        /// </summary>
        internal static string XML_ELEMENT_TOPIC {
            get {
                return ResourceManager.GetString("XML_ELEMENT_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Core/XmlConverter/XmlSchemas/.
        /// </summary>
        internal static string XML_SCHEMA_BASE_URL {
            get {
                return ResourceManager.GetString("XML_SCHEMA_BASE_URL", resourceCulture);
            }
        }
    }
}
