using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace WordToScorm
{
    class Manifest
    {
        public void Write(string FileName)
        {
            FileStream fs = new FileStream(FileName, FileMode.Create);
            StreamWriter sw = new StreamWriter(fs);

            sw.WriteLine("<manifest xmlns=\"http://www.imsglobal.org/xsd/imscp_rootv1p1p2\" xmlns:imsmd=\"http://www.imsglobal.org/xsd/imsmd_rootv1p2p1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.imsglobal.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd\" identifier=\"F41A6835-8E0E-4005-9254-140F62AA346C\">");
            sw.WriteLine("<metadata>");
            sw.WriteLine("<schema>IMS Content</schema> ");
            sw.WriteLine("<schemaversion>1.2</schemaversion> ");
            sw.WriteLine("<imsmd:lom>");
            sw.WriteLine("<imsmd:general>");
            sw.WriteLine("<imsmd:title>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"en-US\">Title</imsmd:langstring> ");
            sw.WriteLine("</imsmd:title>");
            sw.WriteLine("<imsmd:description>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"en-US\" /> ");
            sw.WriteLine("</imsmd:description>");
            sw.WriteLine("<imsmd:language>RU</imsmd:language> ");
            sw.WriteLine("<imsmd:identifier>F41A6835-8E0E-4005-9254-140F62AA346C</imsmd:identifier> ");
            sw.WriteLine("<imsmd:keyword /> ");
            sw.WriteLine("</imsmd:general>");
            sw.WriteLine("<imsmd:educational>");
            sw.WriteLine("<imsmd:description>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"en-US\" /> ");
            sw.WriteLine("</imsmd:description>");
            sw.WriteLine("<imsmd:typicallearningtime>");
            sw.WriteLine("<imsmd:datetime>PT3600S</imsmd:datetime> ");
            sw.WriteLine("</imsmd:typicallearningtime>");
            sw.WriteLine("<imsmd:typicalagerange>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\" /> ");
            sw.WriteLine("</imsmd:typicalagerange>");
            sw.WriteLine("</imsmd:educational>");
            sw.WriteLine("<imsmd:classification>");
            sw.WriteLine("<imsmd:purpose>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">LOMv1.0</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("<imsmd:value>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">Educational Objective</imsmd:langstring> ");
            sw.WriteLine("</imsmd:value>");
            sw.WriteLine("</imsmd:purpose>");
            sw.WriteLine("<imsmd:description>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"en-US\" /> ");
            sw.WriteLine("</imsmd:description>");
            sw.WriteLine("</imsmd:classification>");
            sw.WriteLine("<imsmd:rights /> ");
            sw.WriteLine("<imsmd:metametadata>");
            sw.WriteLine("<imsmd:contribute>");
            sw.WriteLine("<imsmd:role>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">LOMv1.0</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("<imsmd:value>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">Creator</imsmd:langstring> ");
            sw.WriteLine("</imsmd:value>");
            sw.WriteLine("<imsmd:date>");
            sw.WriteLine("<imsmd:datetime>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"\">2007-0-18</imsmd:langstring>"); 
            sw.WriteLine("</imsmd:datetime>");
            sw.WriteLine("</imsmd:date>");
            sw.WriteLine("</imsmd:role>");
            sw.WriteLine("</imsmd:contribute>");
            sw.WriteLine("<imsmd:identifier>CD7E43D2-0C18-4834-B6DD-C02F97F72113</imsmd:identifier> ");
            sw.WriteLine("</imsmd:metametadata>");
            sw.WriteLine("<imsmd:lifecycle>");
            sw.WriteLine("<imsmd:contribute>");
            sw.WriteLine("<imsmd:role>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">LOMv1.0</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("<imsmd:value>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">Unknown</imsmd:langstring> ");
            sw.WriteLine("</imsmd:value>");
            sw.WriteLine("</imsmd:role>");
            sw.WriteLine("<imsmd:date>");
            sw.WriteLine("<imsmd:datetime>2007-0-18</imsmd:datetime> ");
            sw.WriteLine("</imsmd:date>");
            sw.WriteLine("<imsmd:centity>");
            sw.WriteLine("<imsmd:vcard>BEGIN:vCard FN:Author END:vCard</imsmd:vcard> ");
            sw.WriteLine("</imsmd:centity>");
            sw.WriteLine("</imsmd:contribute>");
            sw.WriteLine("<imsmd:contribute>");
            sw.WriteLine("<imsmd:role>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">LOMv1.0</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("<imsmd:value>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">Unknown</imsmd:langstring> ");
            sw.WriteLine("</imsmd:value>");
            sw.WriteLine("</imsmd:role>");
            sw.WriteLine("<imsmd:date>");
            sw.WriteLine("<imsmd:datetime>2007-0-18</imsmd:datetime> ");
            sw.WriteLine("</imsmd:date>");
            sw.WriteLine("<imsmd:centity>");
            sw.WriteLine("<imsmd:vcard>BEGIN:vCard FN:Author END:vCard</imsmd:vcard> ");
            sw.WriteLine("</imsmd:centity>");
            sw.WriteLine("</imsmd:contribute>");
            sw.WriteLine("</imsmd:lifecycle>");
            sw.WriteLine("<imsmd:classification>");
            sw.WriteLine("<imsmd:purpose>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">LOMv1.0</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("<imsmd:value /> ");
            sw.WriteLine("</imsmd:purpose>");
            sw.WriteLine("<imsmd:taxonpath>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">GEM_1201</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("</imsmd:taxonpath>");
            sw.WriteLine("</imsmd:classification>");
            sw.WriteLine("<imsmd:classification>");
            sw.WriteLine("<imsmd:purpose>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">LOMv1.0</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("<imsmd:value>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">Discipline</imsmd:langstring> ");
            sw.WriteLine("</imsmd:value>");
            sw.WriteLine("</imsmd:purpose>");
            sw.WriteLine("<imsmd:taxonpath>");
            sw.WriteLine("<imsmd:source>");
            sw.WriteLine("<imsmd:langstring xml:lang=\"x-none\">GEM_1201</imsmd:langstring> ");
            sw.WriteLine("</imsmd:source>");
            sw.WriteLine("</imsmd:taxonpath>");
            sw.WriteLine("</imsmd:classification>");
            sw.WriteLine("</imsmd:lom>");
            sw.WriteLine("</metadata>");
            sw.WriteLine("<organizations default=\"LRMTOC\">");
            sw.WriteLine("<organization identifier=\"LRMTOC\" structure=\"hierarchical\">");
            sw.WriteLine("<item identifier=\"1000\" identifierref=\"P1000\">");
            sw.WriteLine("<title>Вариант N</title> ");
            sw.WriteLine("</item>");
            sw.WriteLine("</organization>");
            sw.WriteLine("</organizations>");
            sw.WriteLine("<resources>");
            sw.WriteLine("<resource type=\"webcontent\" href=\"Index.xml\">");
            sw.WriteLine("<file href=\"Index.xml\" /> ");
            sw.WriteLine("</resource>");
            sw.WriteLine("<resource identifier=\"P1000\" type=\"webcontent\" href=\"P1000/IMSPage.htm\">");
            sw.WriteLine("<metadata>");
            sw.WriteLine("<imsmd:technical>");
            sw.WriteLine("<imsmd:format>LRM</imsmd:format> ");
            sw.WriteLine("</imsmd:technical>");
            sw.WriteLine("</metadata>");
            sw.WriteLine("<file href=\"P1000/IMSPage.htm\" /> ");
            sw.WriteLine("<file href=\"P1000/page.htm\" /> ");
            sw.WriteLine("<dependency identifierref=\"Shared\" /> ");
            sw.WriteLine("</resource>");
            sw.WriteLine("<resource identifier=\"Shared\" type=\"webcontent\">");
            sw.WriteLine("<metadata>");
            sw.WriteLine("<imsmd:technical>");
            sw.WriteLine("<imsmd:format>LRM</imsmd:format> ");
            sw.WriteLine("</imsmd:technical>");
            sw.WriteLine("</metadata>");
            sw.WriteLine("<file href=\"Shared/themes.css\" /> ");
            sw.WriteLine("</resource>");
            sw.WriteLine("<resource type=\"webcontent\" href=\"Index.xml\">");
            sw.WriteLine("<file href=\"Index.xml\" /> ");
            sw.WriteLine("</resource>");
            sw.WriteLine("</resources>");
            sw.WriteLine("</manifest>");

            sw.Close();
            fs.Close();
        }
    }
}
