//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmkLearningKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VmkLearningKit.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string ABBREVIATION_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("ABBREVIATION_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT_ACTION_NAME {
            get {
                return ResourceManager.GetString("ABOUT_ACTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Chair/.
        /// </summary>
        internal static string ADMIN_CHAIR_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_CHAIR_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Department/.
        /// </summary>
        internal static string ADMIN_DEPARTMENT_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_DEPARTMENT_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/EducationPlan/.
        /// </summary>
        internal static string ADMIN_EDUCATION_PLAN_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_EDUCATION_PLAN_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Group/.
        /// </summary>
        internal static string ADMIN_GROUP_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_GROUP_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminNavigation.
        /// </summary>
        internal static string ADMIN_NAVIGAITON {
            get {
                return ResourceManager.GetString("ADMIN_NAVIGAITON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администраторская панель.
        /// </summary>
        internal static string ADMIN_PANEL_TITLE {
            get {
                return ResourceManager.GetString("ADMIN_PANEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string ADMIN_ROLE {
            get {
                return ResourceManager.GetString("ADMIN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/SpecialityDiscipline/.
        /// </summary>
        internal static string ADMIN_SPECIALITY_DISCIPLINE_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_SPECIALITY_DISCIPLINE_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Speciality/.
        /// </summary>
        internal static string ADMIN_SPECIALITY_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_SPECIALITY_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/Specialization/.
        /// </summary>
        internal static string ADMIN_SPECIALIZATION_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_SPECIALIZATION_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Admin/User/.
        /// </summary>
        internal static string ADMIN_USER_VIEWS {
            get {
                return ResourceManager.GetString("ADMIN_USER_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ALIAS_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("ALIAS_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Cabinet/General/.
        /// </summary>
        internal static string CABINET_GENERAL_VIEWS {
            get {
                return ResourceManager.GetString("CABINET_GENERAL_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Cabinet/Student/.
        /// </summary>
        internal static string CABINET_STUDENT_VIEWS {
            get {
                return ResourceManager.GetString("CABINET_STUDENT_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Cabinet/.
        /// </summary>
        internal static string CABINET_URL {
            get {
                return ResourceManager.GetString("CABINET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Cabinet/.
        /// </summary>
        internal static string CABINET_VIEWS {
            get {
                return ResourceManager.GetString("CABINET_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChairMenu.
        /// </summary>
        internal static string CHAIR_MENU {
            get {
                return ResourceManager.GetString("CHAIR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLK_DBConnectionString.
        /// </summary>
        internal static string CONNECTION_STRING_NAME {
            get {
                return ResourceManager.GetString("CONNECTION_STRING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseName.
        /// </summary>
        internal static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbBackup_.
        /// </summary>
        internal static string DB_BACKUP_NAME {
            get {
                return ResourceManager.GetString("DB_BACKUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /DbBackups/.
        /// </summary>
        internal static string DB_BACKUP_PATH {
            get {
                return ResourceManager.GetString("DB_BACKUP_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbDataFilePath.
        /// </summary>
        internal static string DB_DATA_FILE_PATH {
            get {
                return ResourceManager.GetString("DB_DATA_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbLogFilePath.
        /// </summary>
        internal static string DB_LOG_FILE_PATH {
            get {
                return ResourceManager.GetString("DB_LOG_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана.
        /// </summary>
        internal static string DEFAULT_CHAIR_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_CHAIR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @unn.ru.
        /// </summary>
        internal static string DEFAULT_EMAIL_DOMEN {
            get {
                return ResourceManager.GetString("DEFAULT_EMAIL_DOMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижняя.
        /// </summary>
        internal static string DOWN_WEEK {
            get {
                return ResourceManager.GetString("DOWN_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Error/404.
        /// </summary>
        internal static string ERROR_404_URL {
            get {
                return ResourceManager.GetString("ERROR_404_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Error/.
        /// </summary>
        internal static string ERROR_URL {
            get {
                return ResourceManager.GetString("ERROR_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждая.
        /// </summary>
        internal static string EVERY_WEEK {
            get {
                return ResourceManager.GetString("EVERY_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Uploads/Excel/.
        /// </summary>
        internal static string EXCEL_FILE_UPLOAD_PATH {
            get {
                return ResourceManager.GetString("EXCEL_FILE_UPLOAD_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        internal static string FIELD_MUST_NOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("FIELD_MUST_NOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string FORM_MESSAGE {
            get {
                return ResourceManager.GetString("FORM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralMenu.
        /// </summary>
        internal static string GENERAL_MENU {
            get {
                return ResourceManager.GetString("GENERAL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralNavigation.
        /// </summary>
        internal static string GENERAL_NAVIGATION {
            get {
                return ResourceManager.GetString("GENERAL_NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string GROUP_DEFAULT_ALIAS {
            get {
                return ResourceManager.GetString("GROUP_DEFAULT_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        internal static string HASH_ALGORITHM {
            get {
                return ResourceManager.GetString("HASH_ALGORITHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home.
        /// </summary>
        internal static string HOME_URL {
            get {
                return ResourceManager.GetString("HOME_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuType.
        /// </summary>
        internal static string MENU_TYPE {
            get {
                return ResourceManager.GetString("MENU_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodist.
        /// </summary>
        internal static string METODIST_ROLE {
            get {
                return ResourceManager.GetString("METODIST_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationType.
        /// </summary>
        internal static string NAVIGATION_TYPE {
            get {
                return ResourceManager.GetString("NAVIGATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NONE_ROLE {
            get {
                return ResourceManager.GetString("NONE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageTitle.
        /// </summary>
        internal static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartialViewError.
        /// </summary>
        internal static string PARTIALVIEW_PAGE_ERROR {
            get {
                return ResourceManager.GetString("PARTIALVIEW_PAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        internal static string PERSON_CABINET {
            get {
                return ResourceManager.GetString("PERSON_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_ABOUT {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_DEGREE {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor_None.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_LOGIN {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor_None.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_NICKNAME {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана.
        /// </summary>
        internal static string PROFESSOR_DEFAULT_POSITION {
            get {
                return ResourceManager.GetString("PROFESSOR_DEFAULT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfessorMenu.
        /// </summary>
        internal static string PROFESSOR_MENU {
            get {
                return ResourceManager.GetString("PROFESSOR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string PROFESSOR_ROLE {
            get {
                return ResourceManager.GetString("PROFESSOR_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professors.
        /// </summary>
        internal static string PROFESSORS_ACTION_NAME {
            get {
                return ResourceManager.GetString("PROFESSORS_ACTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([1-9]\d*\.\d+)|([1-9]\d*)|([0])|([0]\.d+).
        /// </summary>
        internal static string REGULAR_EXPRESSION_VALUE_WITH_POINT {
            get {
                return ResourceManager.GetString("REGULAR_EXPRESSION_VALUE_WITH_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SESSION_USER {
            get {
                return ResourceManager.GetString("SESSION_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAuth.
        /// </summary>
        internal static string SESSION_USER_AUTH {
            get {
                return ResourceManager.GetString("SESSION_USER_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLogin.
        /// </summary>
        internal static string SESSION_USER_LOGIN {
            get {
                return ResourceManager.GetString("SESSION_USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string SESSION_USER_NAME {
            get {
                return ResourceManager.GetString("SESSION_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole.
        /// </summary>
        internal static string SESSION_USER_ROLE {
            get {
                return ResourceManager.GetString("SESSION_USER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальности и специализации.
        /// </summary>
        internal static string SPECIALITIES_TITLE {
            get {
                return ResourceManager.GetString("SPECIALITIES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialityAlias.
        /// </summary>
        internal static string SPECIALITY_ALIAS {
            get {
                return ResourceManager.GetString("SPECIALITY_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано.
        /// </summary>
        internal static string STRING_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("STRING_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studnet_None.
        /// </summary>
        internal static string STUDENT_DEFAULT_LOGIN {
            get {
                return ResourceManager.GetString("STUDENT_DEFAULT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student_None.
        /// </summary>
        internal static string STUDENT_DEFAULT_NICKNAME {
            get {
                return ResourceManager.GetString("STUDENT_DEFAULT_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        internal static string STUDENT_DEFAULT_SECOND_NAME {
            get {
                return ResourceManager.GetString("STUDENT_DEFAULT_SECOND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string STUDENT_ROLE {
            get {
                return ResourceManager.GetString("STUDENT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Cabinet/Timetable/.
        /// </summary>
        internal static string STUDENT_TIMETABLE_URL {
            get {
                return ResourceManager.GetString("STUDENT_TIMETABLE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано.
        /// </summary>
        internal static string TERM_DEFAULT_REPORTING {
            get {
                return ResourceManager.GetString("TERM_DEFAULT_REPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхняя.
        /// </summary>
        internal static string UP_WEEK {
            get {
                return ResourceManager.GetString("UP_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string VIEW_PAGE_ERROR {
            get {
                return ResourceManager.GetString("VIEW_PAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error404.
        /// </summary>
        internal static string VIEW_PAGE_ERROR_404 {
            get {
                return ResourceManager.GetString("VIEW_PAGE_ERROR_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMK.
        /// </summary>
        internal static string VMK_DEPARTMENT_ALIAS {
            get {
                return ResourceManager.GetString("VMK_DEPARTMENT_ALIAS", resourceCulture);
            }
        }
    }
}
