//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnnLearningKit {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebConstants() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnnLearningKit.WebConstants", typeof(WebConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddGroup.aspx?DepartmentID=.
        /// </summary>
        internal static string AddGroupUrl {
            get {
                return ResourceManager.GetString("AddGroupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddStudent.aspx?GroupID=.
        /// </summary>
        internal static string AddStudentUrl {
            get {
                return ResourceManager.GetString("AddStudentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CreateAccount.aspx.
        /// </summary>
        internal static string CreateAccountUrl {
            get {
                return ResourceManager.GetString("CreateAccountUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeleteAccountResult.aspx.
        /// </summary>
        internal static string DeleteAccountResultUrl {
            get {
                return ResourceManager.GetString("DeleteAccountResultUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeleteStudentResult.aspx.
        /// </summary>
        internal static string DeleteStudentResultUrl {
            get {
                return ResourceManager.GetString("DeleteStudentResultUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EditAccountResult.aspx.
        /// </summary>
        internal static string EditAccountResultUrl {
            get {
                return ResourceManager.GetString("EditAccountResultUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EditStudentResult.aspx.
        /// </summary>
        internal static string EditStudentResultUrl {
            get {
                return ResourceManager.GetString("EditStudentResultUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FullUserName.
        /// </summary>
        internal static string FullUserNameControlName {
            get {
                return ResourceManager.GetString("FullUserNameControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на groupsList.
        /// </summary>
        internal static string GroupsListControlName {
            get {
                return ResourceManager.GetString("GroupsListControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ManageGroups.aspx?DepartmentID=.
        /// </summary>
        internal static string GroupsUrl {
            get {
                return ResourceManager.GetString("GroupsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hideMessage.
        /// </summary>
        internal static string HideMessageCssClass {
            get {
                return ResourceManager.GetString("HideMessageCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ManageAccounts.aspx.
        /// </summary>
        internal static string MangeAccountsUrl {
            get {
                return ResourceManager.GetString("MangeAccountsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rolesList.
        /// </summary>
        internal static string RolesListControlName {
            get {
                return ResourceManager.GetString("RolesListControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answer.
        /// </summary>
        internal static string SecretAnswerControlName {
            get {
                return ResourceManager.GetString("SecretAnswerControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на showMessage.
        /// </summary>
        internal static string ShowMessageCssClass {
            get {
                return ResourceManager.GetString("ShowMessageCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ManageStudents.aspx?GroupID=.
        /// </summary>
        internal static string StudentsUrl {
            get {
                return ResourceManager.GetString("StudentsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string UserDescriptionControlName {
            get {
                return ResourceManager.GetString("UserDescriptionControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        internal static string UsersGroupRoleName {
            get {
                return ResourceManager.GetString("UsersGroupRoleName", resourceCulture);
            }
        }
    }
}
